/* MiniScheme5.java */
/* Generated By:JavaCC: Do not edit this line. MiniScheme5.java */
import java.util.Scanner;
import java.io.FileInputStream;
import java.io.FileNotFoundException;

public class MiniScheme5 implements MiniScheme5Constants {
  public static Scanner in;

  public static void main(String args[]) throws ParseException
  {
    try {
      MiniScheme5 parser = null;
      in = new Scanner(System.in);
      if (args.length > 0)
      parser = new MiniScheme5(new FileInputStream(args[0]));
      else
      {
        System.out.print("Program filename: ");
        parser = new MiniScheme5(new FileInputStream(in.nextLine()));
       }
      Program p = parser.program();
      p.eval(new Env());
      //p.print();
    }
    catch (FileNotFoundException e)
    {
      System.out.println(e.getMessage());
    }
    catch (RuntimeException e)
    {
      System.out.println(e.getMessage());
      e.printStackTrace();
    }
  }

  static final public Program program() throws ParseException {Program p = new Program(); Exp e = null; Definition d = null;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INTEGER:
      case BOOLEAN:
      case IDENTIFIER:
      case 35:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      if (jj_2_1(2147483647)) {
        d = def();
p.lineList.add(d);
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case INTEGER:
        case BOOLEAN:
        case IDENTIFIER:
        case 35:{
          e = exp();
p.lineList.add(e);
          break;
          }
        default:
          jj_la1[1] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
{if ("" != null) return p;}
    throw new Error("Missing return statement in function");
}

  static final public Definition def() throws ParseException {Definition d = null; Variable var = null; Exp e = null;
    jj_consume_token(35);
    jj_consume_token(DEFINE);
    var = variable();
    e = exp();
    jj_consume_token(36);
d = new Definition(var, e);
{if ("" != null) return d;}
    throw new Error("Missing return statement in function");
}

  static final public Exp exp() throws ParseException {Exp e = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFIER:{
      e = variable();
      break;
      }
    case INTEGER:
    case BOOLEAN:{
      e = literal();
      break;
      }
    case 35:{
      jj_consume_token(35);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IF:{
        e = cond();
        break;
        }
      case SET:{
        e = assign();
        break;
        }
      case PLUS:
      case MINUS:
      case MULTIPLY:
      case QUOTIENT:
      case READ:
      case WRITE:
      case NEWLINE:
      case LET:
      case AND:
      case OR:
      case NOT:
      case EQV_CHECK:
      case LESS_THAN:
      case INT_CHECK:
      case BOOL_CHECK:
      case PAIR_CHECK:
      case CONS_PAIR:
      case CONS_LIST:
      case NULL_CHECK:
      case CAR:{
        e = derivedExpression();
        break;
        }
      case LAMBDA:{
        e = lambdaExp();
        break;
        }
      case INTEGER:
      case BOOLEAN:
      case IDENTIFIER:
      case 35:{
        e = procCall();
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(36);
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return e;}
    throw new Error("Missing return statement in function");
}

  static final public Variable variable() throws ParseException {Variable var = null; String id = null;
    jj_consume_token(IDENTIFIER);
id = token.image; var = new Variable(id);
{if ("" != null) return var;}
    throw new Error("Missing return statement in function");
}

  static final public Literal literal() throws ParseException {Literal l = null; String s = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INTEGER:{
      jj_consume_token(INTEGER);
s = token.image; l = new Int(s);
      break;
      }
    case BOOLEAN:{
      jj_consume_token(BOOLEAN);
s = token.image; l = new Bool(s);
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return l;}
    throw new Error("Missing return statement in function");
}

  static final public Cond cond() throws ParseException {Cond c = null; Exp e1 = null; Exp e2 = null; Exp e3 = null;
    jj_consume_token(IF);
    e1 = exp();
    e2 = exp();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INTEGER:
    case BOOLEAN:
    case IDENTIFIER:
    case 35:{
      e3 = exp();
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      ;
    }
c = new Cond(e1, e2, e3); {if ("" != null) return c;}
    throw new Error("Missing return statement in function");
}

  static final public Assignment assign() throws ParseException {Assignment a = null; Variable var = null; Exp e = null;
    jj_consume_token(SET);
    var = variable();
    e = exp();
a = new Assignment(var, e);
{if ("" != null) return a;}
    throw new Error("Missing return statement in function");
}

  static final public Exp derivedExpression() throws ParseException {Token t = null; Exp e1 = null; Exp e2 = null;
  WriteExpression we = null; ArithExp ae = null;
  ReadExpression re = null; NewlineExpression nl = null;
  LetExp le = null; BindSpec bi = null; Body bod = null;
  AndExp andE = null; OrExp orE = null; List lst = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case READ:{
      jj_consume_token(READ);
re = new ReadExpression(in); e1 = re;
      break;
      }
    case WRITE:{
      jj_consume_token(WRITE);
      e1 = exp();
we = new WriteExpression(e1); e1 = we;
      break;
      }
    case NEWLINE:{
      jj_consume_token(NEWLINE);
nl = new NewlineExpression(); e1 = nl;
      break;
      }
    case PLUS:
    case MINUS:
    case MULTIPLY:
    case QUOTIENT:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:{
        jj_consume_token(PLUS);
        break;
        }
      case MINUS:{
        jj_consume_token(MINUS);
        break;
        }
      case MULTIPLY:{
        jj_consume_token(MULTIPLY);
        break;
        }
      case QUOTIENT:{
        jj_consume_token(QUOTIENT);
        break;
        }
      default:
        jj_la1[6] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
t = token;
      e1 = exp();
      e2 = exp();
ae = new ArithExp(t.image, e1, e2); e1 = ae;
      break;
      }
    case LET:{
      jj_consume_token(LET);
le = new LetExp();
      jj_consume_token(35);
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 35:{
          ;
          break;
          }
        default:
          jj_la1[7] = jj_gen;
          break label_2;
        }
        bi = bindSpec();
le.binds.add(bi);
      }
      jj_consume_token(36);
      bod = body();
le.body = bod; e1=le;
      break;
      }
    case AND:{
      jj_consume_token(AND);
andE = new AndExp();
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case INTEGER:
        case BOOLEAN:
        case IDENTIFIER:
        case 35:{
          ;
          break;
          }
        default:
          jj_la1[8] = jj_gen;
          break label_3;
        }
        e1 = exp();
andE.expList.add(e1);
      }
e1 = andE;
      break;
      }
    case OR:{
      jj_consume_token(OR);
orE = new OrExp();
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case INTEGER:
        case BOOLEAN:
        case IDENTIFIER:
        case 35:{
          ;
          break;
          }
        default:
          jj_la1[9] = jj_gen;
          break label_4;
        }
        e1 = exp();
orE.expList.add(e1);
      }
e1 = orE;
      break;
      }
    case NOT:{
      jj_consume_token(NOT);
      e1 = exp();
e1 = new NotExp(e1);
      break;
      }
    case EQV_CHECK:{
      jj_consume_token(EQV_CHECK);
      e1 = exp();
      e2 = exp();
e1 = new EqvExp(e1, e2);
      break;
      }
    case LESS_THAN:{
      jj_consume_token(LESS_THAN);
      e1 = exp();
      e2 = exp();
e1 = new LessExp(e1, e2);
      break;
      }
    case INT_CHECK:{
      jj_consume_token(INT_CHECK);
      e1 = exp();
e1 = new IntCheckExp(e1);
      break;
      }
    case BOOL_CHECK:{
      jj_consume_token(BOOL_CHECK);
      e1 = exp();
e1 = new BoolCheckExp(e1);
      break;
      }
    case PAIR_CHECK:{
      jj_consume_token(PAIR_CHECK);
      e1 = exp();
e1 = new PairCheckExp(e1);
      break;
      }
    case CONS_PAIR:{
      jj_consume_token(CONS_PAIR);
      e1 = exp();
      e2 = exp();
e1 = new Pair(e1, e2);
      break;
      }
    case CONS_LIST:{
      jj_consume_token(CONS_LIST);
lst = new List();
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case INTEGER:
        case BOOLEAN:
        case IDENTIFIER:
        case 35:{
          ;
          break;
          }
        default:
          jj_la1[10] = jj_gen;
          break label_5;
        }
        e1 = exp();
lst.addList(e1);
      }
e1=lst;
      break;
      }
    case NULL_CHECK:{
      jj_consume_token(NULL_CHECK);
      e1 = exp();
e1 = new NullCheckExp(e1);
      break;
      }
    case CAR:{
      jj_consume_token(CAR);
      e1 = exp();
e1 = new CarExp(e1);
      break;
      }
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return e1;}
    throw new Error("Missing return statement in function");
}

  static final public BindSpec bindSpec() throws ParseException {Variable var = null; Exp e = null;
    jj_consume_token(35);
    var = variable();
    e = exp();
    jj_consume_token(36);
{if ("" != null) return new BindSpec(var, e);}
    throw new Error("Missing return statement in function");
}

  static final public Body body() throws ParseException {Body bod = new Body(); Definition def = null; Exp exp = null;
    label_6:
    while (true) {
      if (jj_2_2(2147483647)) {
        ;
      } else {
        break label_6;
      }
      def = def();
bod.lines.add(def);
    }
    label_7:
    while (true) {
      exp = exp();
bod.lines.add(exp);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INTEGER:
      case BOOLEAN:
      case IDENTIFIER:
      case 35:{
        ;
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        break label_7;
      }
    }
{if ("" != null) return bod;}
    throw new Error("Missing return statement in function");
}

  static final public LambdaExp lambdaExp() throws ParseException {LambdaExp l = new LambdaExp(); Variable v = null; Body b = null;
    jj_consume_token(LAMBDA);
    jj_consume_token(35);
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFIER:{
        ;
        break;
        }
      default:
        jj_la1[13] = jj_gen;
        break label_8;
      }
      v = variable();
l.varList.add(v);
    }
    jj_consume_token(36);
    b = body();
l.body = b;
{if ("" != null) return l;}
    throw new Error("Missing return statement in function");
}

  static final public ProcCall procCall() throws ParseException {ProcCall p = new ProcCall(); Exp e = null;
    label_9:
    while (true) {
      e = exp();
p.expList.add(e);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INTEGER:
      case BOOLEAN:
      case IDENTIFIER:
      case 35:{
        ;
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        break label_9;
      }
    }
{if ("" != null) return p;}
    throw new Error("Missing return statement in function");
}

  static private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_3R_derivedExpression_184_5_43()
 {
    if (jj_scan_token(CONS_PAIR)) return true;
    if (jj_3R_exp_124_9_12()) return true;
    if (jj_3R_exp_124_9_12()) return true;
    return false;
  }

  static private boolean jj_3R_derivedExpression_183_5_42()
 {
    if (jj_scan_token(PAIR_CHECK)) return true;
    if (jj_3R_exp_124_9_12()) return true;
    return false;
  }

  static private boolean jj_3R_derivedExpression_182_5_41()
 {
    if (jj_scan_token(BOOL_CHECK)) return true;
    if (jj_3R_exp_124_9_12()) return true;
    return false;
  }

  static private boolean jj_3R_derivedExpression_181_5_40()
 {
    if (jj_scan_token(INT_CHECK)) return true;
    if (jj_3R_exp_124_9_12()) return true;
    return false;
  }

  static private boolean jj_3R_derivedExpression_180_5_39()
 {
    if (jj_scan_token(LESS_THAN)) return true;
    if (jj_3R_exp_124_9_12()) return true;
    if (jj_3R_exp_124_9_12()) return true;
    return false;
  }

  static private boolean jj_3R_derivedExpression_179_5_38()
 {
    if (jj_scan_token(EQV_CHECK)) return true;
    if (jj_3R_exp_124_9_12()) return true;
    if (jj_3R_exp_124_9_12()) return true;
    return false;
  }

  static private boolean jj_3R_derivedExpression_178_5_37()
 {
    if (jj_scan_token(NOT)) return true;
    if (jj_3R_exp_124_9_12()) return true;
    return false;
  }

  static private boolean jj_3R_derivedExpression_177_5_36()
 {
    if (jj_scan_token(OR)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_derivedExpression_177_37_52()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_cond_152_29_29()
 {
    if (jj_3R_exp_124_9_12()) return true;
    return false;
  }

  static private boolean jj_3R_derivedExpression_176_5_35()
 {
    if (jj_scan_token(AND)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_derivedExpression_176_40_51()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_derivedExpression_175_5_34()
 {
    if (jj_scan_token(LET)) return true;
    if (jj_scan_token(35)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_derivedExpression_175_42_50()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(36)) return true;
    if (jj_3R_body_202_3_48()) return true;
    return false;
  }

  static private boolean jj_3R_derivedExpression_174_5_33()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(5)) {
    jj_scanpos = xsp;
    if (jj_scan_token(6)) {
    jj_scanpos = xsp;
    if (jj_scan_token(7)) {
    jj_scanpos = xsp;
    if (jj_scan_token(8)) return true;
    }
    }
    }
    if (jj_3R_exp_124_9_12()) return true;
    if (jj_3R_exp_124_9_12()) return true;
    return false;
  }

  static private boolean jj_3R_derivedExpression_173_5_32()
 {
    if (jj_scan_token(NEWLINE)) return true;
    return false;
  }

  static private boolean jj_3R_derivedExpression_172_5_31()
 {
    if (jj_scan_token(WRITE)) return true;
    if (jj_3R_exp_124_9_12()) return true;
    return false;
  }

  static private boolean jj_3R_derivedExpression_171_5_30()
 {
    if (jj_scan_token(READ)) return true;
    return false;
  }

  static private boolean jj_3R_derivedExpression_170_3_26()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_derivedExpression_171_5_30()) {
    jj_scanpos = xsp;
    if (jj_3R_derivedExpression_172_5_31()) {
    jj_scanpos = xsp;
    if (jj_3R_derivedExpression_173_5_32()) {
    jj_scanpos = xsp;
    if (jj_3R_derivedExpression_174_5_33()) {
    jj_scanpos = xsp;
    if (jj_3R_derivedExpression_175_5_34()) {
    jj_scanpos = xsp;
    if (jj_3R_derivedExpression_176_5_35()) {
    jj_scanpos = xsp;
    if (jj_3R_derivedExpression_177_5_36()) {
    jj_scanpos = xsp;
    if (jj_3R_derivedExpression_178_5_37()) {
    jj_scanpos = xsp;
    if (jj_3R_derivedExpression_179_5_38()) {
    jj_scanpos = xsp;
    if (jj_3R_derivedExpression_180_5_39()) {
    jj_scanpos = xsp;
    if (jj_3R_derivedExpression_181_5_40()) {
    jj_scanpos = xsp;
    if (jj_3R_derivedExpression_182_5_41()) {
    jj_scanpos = xsp;
    if (jj_3R_derivedExpression_183_5_42()) {
    jj_scanpos = xsp;
    if (jj_3R_derivedExpression_184_5_43()) {
    jj_scanpos = xsp;
    if (jj_3R_derivedExpression_185_5_44()) {
    jj_scanpos = xsp;
    if (jj_3R_derivedExpression_186_5_45()) {
    jj_scanpos = xsp;
    if (jj_3R_derivedExpression_187_5_46()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_exp_127_44_19()
 {
    if (jj_3R_derivedExpression_170_3_26()) return true;
    return false;
  }

  static private boolean jj_3R_assign_159_3_25()
 {
    if (jj_scan_token(SET)) return true;
    if (jj_3R_variable_135_3_11()) return true;
    if (jj_3R_exp_124_9_12()) return true;
    return false;
  }

  static private boolean jj_3R_exp_127_31_18()
 {
    if (jj_3R_assign_159_3_25()) return true;
    return false;
  }

  static private boolean jj_3R_cond_152_3_24()
 {
    if (jj_scan_token(IF)) return true;
    if (jj_3R_exp_124_9_12()) return true;
    if (jj_3R_exp_124_9_12()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_cond_152_29_29()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_literal_144_5_23()
 {
    if (jj_scan_token(BOOLEAN)) return true;
    return false;
  }

  static private boolean jj_3R_literal_143_5_22()
 {
    if (jj_scan_token(INTEGER)) return true;
    return false;
  }

  static private boolean jj_3R_exp_127_20_17()
 {
    if (jj_3R_cond_152_3_24()) return true;
    return false;
  }

  static private boolean jj_3R_literal_142_3_16()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_literal_143_5_22()) {
    jj_scanpos = xsp;
    if (jj_3R_literal_144_5_23()) return true;
    }
    return false;
  }

  static private boolean jj_3R_exp_125_19_13()
 {
    if (jj_3R_variable_135_3_11()) return true;
    return false;
  }

  static private boolean jj_3R_exp_127_15_15()
 {
    if (jj_scan_token(35)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_exp_127_20_17()) {
    jj_scanpos = xsp;
    if (jj_3R_exp_127_31_18()) {
    jj_scanpos = xsp;
    if (jj_3R_exp_127_44_19()) {
    jj_scanpos = xsp;
    if (jj_3R_exp_127_68_20()) {
    jj_scanpos = xsp;
    if (jj_3R_exp_127_84_21()) return true;
    }
    }
    }
    }
    if (jj_scan_token(36)) return true;
    return false;
  }

  static private boolean jj_3R_exp_126_15_14()
 {
    if (jj_3R_literal_142_3_16()) return true;
    return false;
  }

  static private boolean jj_3R_variable_135_3_11()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3R_lambdaExp_212_19_47()
 {
    if (jj_3R_variable_135_3_11()) return true;
    return false;
  }

  static private boolean jj_3R_derivedExpression_185_43_53()
 {
    if (jj_3R_exp_124_9_12()) return true;
    return false;
  }

  static private boolean jj_3R_exp_124_9_12()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_exp_125_19_13()) {
    jj_scanpos = xsp;
    if (jj_3R_exp_126_15_14()) {
    jj_scanpos = xsp;
    if (jj_3R_exp_127_15_15()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_procCall_219_4_49()
 {
    if (jj_3R_exp_124_9_12()) return true;
    return false;
  }

  static private boolean jj_3R_procCall_219_3_28()
 {
    Token xsp;
    if (jj_3R_procCall_219_4_49()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_procCall_219_4_49()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3_1()
 {
    if (jj_3R_def_117_3_10()) return true;
    return false;
  }

  static private boolean jj_3_2()
 {
    if (jj_3R_def_117_3_10()) return true;
    return false;
  }

  static private boolean jj_3R_derivedExpression_175_42_50()
 {
    if (jj_3R_bindSpec_195_3_56()) return true;
    return false;
  }

  static private boolean jj_3R_derivedExpression_176_40_51()
 {
    if (jj_3R_exp_124_9_12()) return true;
    return false;
  }

  static private boolean jj_3R_def_117_3_10()
 {
    if (jj_scan_token(35)) return true;
    if (jj_scan_token(DEFINE)) return true;
    if (jj_3R_variable_135_3_11()) return true;
    if (jj_3R_exp_124_9_12()) return true;
    if (jj_scan_token(36)) return true;
    return false;
  }

  static private boolean jj_3R_lambdaExp_212_3_27()
 {
    if (jj_scan_token(LAMBDA)) return true;
    if (jj_scan_token(35)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_lambdaExp_212_19_47()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(36)) return true;
    if (jj_3R_body_202_3_48()) return true;
    return false;
  }

  static private boolean jj_3R_derivedExpression_177_37_52()
 {
    if (jj_3R_exp_124_9_12()) return true;
    return false;
  }

  static private boolean jj_3R_exp_127_84_21()
 {
    if (jj_3R_procCall_219_3_28()) return true;
    return false;
  }

  static private boolean jj_3R_body_204_6_55()
 {
    if (jj_3R_exp_124_9_12()) return true;
    return false;
  }

  static private boolean jj_3R_body_203_6_54()
 {
    if (jj_3R_def_117_3_10()) return true;
    return false;
  }

  static private boolean jj_3R_body_202_3_48()
 {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_body_203_6_54()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_body_204_6_55()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_body_204_6_55()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_bindSpec_195_3_56()
 {
    if (jj_scan_token(35)) return true;
    if (jj_3R_variable_135_3_11()) return true;
    if (jj_3R_exp_124_9_12()) return true;
    if (jj_scan_token(36)) return true;
    return false;
  }

  static private boolean jj_3R_exp_127_68_20()
 {
    if (jj_3R_lambdaExp_212_3_27()) return true;
    return false;
  }

  static private boolean jj_3R_derivedExpression_187_5_46()
 {
    if (jj_scan_token(CAR)) return true;
    if (jj_3R_exp_124_9_12()) return true;
    return false;
  }

  static private boolean jj_3R_derivedExpression_186_5_45()
 {
    if (jj_scan_token(NULL_CHECK)) return true;
    if (jj_3R_exp_124_9_12()) return true;
    return false;
  }

  static private boolean jj_3R_derivedExpression_185_5_44()
 {
    if (jj_scan_token(CONS_LIST)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_derivedExpression_185_43_53()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public MiniScheme5TokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[15];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0xa00,0xa00,0xffff7be0,0xa00,0xa00,0xa00,0x1e0,0x0,0xa00,0xa00,0xa00,0xfbf971e0,0xa00,0x0,0xa00,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x9,0x9,0x9,0x9,0x0,0x9,0x0,0x8,0x9,0x9,0x9,0x0,0x9,0x1,0x9,};
	}
  static final private JJCalls[] jj_2_rtns = new JJCalls[2];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public MiniScheme5(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public MiniScheme5(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new MiniScheme5TokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 15; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 15; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public MiniScheme5(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new MiniScheme5TokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 15; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new MiniScheme5TokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 15; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public MiniScheme5(MiniScheme5TokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 15; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(MiniScheme5TokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 15; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[37];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 15; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 37; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 2; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}
