/* Generated By:JavaCC: Do not edit this line. MiniScheme2Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniScheme2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int MULTIPLY = 7;
  /** RegularExpression Id. */
  int QUOTIENT = 8;
  /** RegularExpression Id. */
  int INTEGER = 9;
  /** RegularExpression Id. */
  int DIGIT = 10;
  /** RegularExpression Id. */
  int READ = 11;
  /** RegularExpression Id. */
  int WRITE = 12;
  /** RegularExpression Id. */
  int NEWLINE = 13;
  /** RegularExpression Id. */
  int DEFINE = 14;
  /** RegularExpression Id. */
  int LET = 15;
  /** RegularExpression Id. */
  int SET = 16;
  /** RegularExpression Id. */
  int IDENTIFIER = 17;
  /** RegularExpression Id. */
  int INITIAL = 18;
  /** RegularExpression Id. */
  int SUBSEQUENT = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"quotient\"",
    "<INTEGER>",
    "<DIGIT>",
    "\"read\"",
    "\"write\"",
    "\"newline\"",
    "\"define\"",
    "\"let\"",
    "\"set!\"",
    "<IDENTIFIER>",
    "<INITIAL>",
    "<SUBSEQUENT>",
    "\"(\"",
    "\")\"",
  };

}
